spring.application.name=transport

spring.datasource.url=jdbc:postgresql://localhost:5432/passagens
spring.datasource.username=postgres
spring.datasource.password=1234


spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
api.ibge.url-estados=https://servicodados.ibge.gov.br/api/v1/localidades/estados
api.security.token.secret=UMAVEZflamengoFlamengoATEMORRER2019198120222025
# Configurações do Servidor de E-mail Real (Exemplo: Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=celsosilvavinicius151@gmail.com
spring.mail.password=kebd dmyx oodg ntjg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

